HEADER:
  label: "About me"

PRESENTATION:
  description: |
    I'm a Software Engineer from Taiwan, passionate about Computer Vision, Machine Learning, and Visual related Technologies. With solid experience in machine learning, software systems development, and full-stack web applications.
    
    I recently graduated from The Hong Kong University of Science and Technology with a BEng in Computer Engineering and a minor in Big Data Technology. 
    Currently, I work as a Research Assistant at Academia Sinica, where I contribute to cutting-edge research projects.  

    Feel free to connect and get in touch with me :)

DOING:
  enabled: true
  label: "What I'm doing | Interested in"
  items:
    - title: "Computer Vision"
      icon: "config/assets/icons/mobile.svg"
      description: "Developing real-time object detection and tracking systems with YOLO; researching generative AI for advanced image synthesis."
    - title: "Machine Learning"
      icon: "config/assets/icons/code.svg"
      description: "Investigating state-of-the-art NLP and deep learning architectures—including transformer-based models—for practical applications."
    - title: "Computer Architecture"
      icon: "config/assets/icons/compass.svg"
      description: "Optimizing GPU-accelerated parallel-compute frameworks and exploring hardware-software co-design for high-performance systems."
    - title: "Computer Graphics"
      icon: "config/assets/icons/laptop-code.svg"
      description: "Studying graphics pipelines at both software and hardware levels, from real-time shader development to GPU rendering optimization."


SKILLS:
  enabled: true
  label: "Soft Skills"
  items:
    - title: "Fast Learner"
      icon: "config/assets/icons/bolt.svg"
      description: "I have the ability to quickly acquire new knowledge and adapt to changing technological environments."
    - title: "Teamwork"
      icon: "config/assets/icons/user.svg"
      description: "I collaborate effectively in multidisciplinary projects and communicate clearly with team members."
    - title: "Problem Solving"
      icon: "config/assets/icons/gear.svg"
      description: "I am creative and efficient in identifying and solving technical problems."
    - title: "Effective Communication"
      icon: "config/assets/icons/comment.svg"
      description: "I have the skill to convey ideas clearly and concisely, both technically and non-technically."

TECHNOLOGIES:
  enabled: true
  label: "Tech Experience"
  items:
    - title: "Python"
      icon: "config/assets/icons/python.svg"
    - title: "C++"
      icon: "config/assets/icons/flutter.svg"
    - title: "Git"
      icon: "config/assets/icons/git.svg"
    - title: "Figma"
      icon: "config/assets/icons/figma.svg"
    - title: "TensorFlow"
      icon: "config/assets/icons/firebase.svg"
    - title: "Pandas"
      icon: "config/assets/icons/pandas.svg"
    - title: "PyTorch"
      icon: "config/assets/icons/mongodb.svg"
    - title: "Numpy"
      icon: "config/assets/icons/dart.svg"
    - title: "Apache Spark"
      icon: "config/assets/icons/html.svg"
    - title: "Docker"
      icon: "config/assets/icons/ai.svg"
    - title: "AWS Cloud Computing"
      icon: "config/assets/icons/jupyter.svg"
    - title: "Linux"
      icon: "config/assets/icons/linux.svg"
    - title: "Apache Hadoop"
    - title: "TypeScript"
    - title: "JavaScript"
    - title: "React"
    - title: "C"
    - title: "Java"
    - title: "MATLAB"
    - title: "MIPS"
    - title: "Adobe Illustrator"
    - title: "Final Cut Pro"
    - title: "Notion"
    - title: "Anaconda"
    - title: "LaTeX"
