HEADER:
  label: "About me"

PRESENTATION:
  description: |
    I'm a Software Engineer from Taiwan, passionate about Computer Vision, Machine Learning, and Visual related Technologies. With solid experience in machine learning, software systems development, and full-stack web applications.
    
    I recently graduated from The Hong Kong University of Science and Technology with a BEng in Computer Engineering and a minor in Big Data Technology. 
    Currently, I work as a Research Assistant at Academia Sinica, where I contribute to cutting-edge research projects.  

    Feel free to connect and get in touch with me :)

DOING:
  enabled: true
  label: "What I'm doing | Interested in"
  items:
    - title: "Computer Vision"
      icon: "tv"
      # icon: "config/assets/icons/mobile.svg"
      description: "Developing real-time object detection and tracking systems with YOLO; researching generative AI for advanced image synthesis."
    - title: "Machine Learning"
      icon: "code-slash"
      description: "Investigating state-of-the-art NLP and deep learning architectures—including transformer-based models—for practical applications."
    - title: "Computer Architecture"
      icon: "terminal"
      description: "Optimizing GPU-accelerated parallel-compute frameworks and exploring hardware-software co-design for high-performance systems."
    - title: "Computer Graphics"
      icon: "film"
      description: "Studying graphics pipelines at both software and hardware levels, from real-time shader development to GPU rendering optimization."


SKILLS:
  enabled: true
  label: "Soft Skills"
  items:
    - title: "Fast Learner"
      icon: "config/assets/icons/flash.svg"
      description: "I have the ability to quickly acquire new knowledge and adapt to changing technological environments."
    - title: "Teamwork"
      icon: "config/assets/icons/people.svg"
      description: "I collaborate effectively in multidisciplinary projects and communicate clearly with team members."
    - title: "Problem Solving"
      icon: "config/assets/icons/setting.svg"
      description: "I am creative and efficient in identifying and solving technical problems."
    - title: "Effective Communication"
      icon: "config/assets/icons/chatbubbles.svg"
      description: "I have the skill to convey ideas clearly and concisely, both technically and non-technically."

TECHNOLOGIES:
  enabled: true
  label: "Tech Experience"
  items:
    - title: "Python"
      icon: "config/assets/icons/python.svg"
    - title: "C++"
      icon: "config/assets/icons/cpp.svg"
    - title: "C"
      icon: "config/assets/icons/c.svg"
    - title: "Java"
      icon: "config/assets/icons/java.svg"
    - title: "Git"
      icon: "config/assets/icons/git.svg"
    - title: "TensorFlow"
      icon: "config/assets/icons/tensorflow.svg"
    - title: "Pandas"
      icon: "config/assets/icons/pandas.svg"
    - title: "PyTorch"
      icon: "config/assets/icons/pytorch.svg"
    - title: "Numpy"
      icon: "config/assets/icons/numpy.svg"
    - title: "Apache Spark"
    - title: "Apache Hadoop"
      icon: "config/assets/icons/hadoop.svg"
    - title: "Docker"
      icon: "config/assets/icons/docker.svg"
    - title: "CUDA"
      icon: "config/assets/icons/cuda.svg"
    - title: "AWS Cloud Computing"
      icon: "config/assets/icons/aws.svg"
    - title: "Linux"
      icon: "config/assets/icons/linux.svg"
    - title: "TypeScript"
      icon: "config/assets/icons/typescript.svg"
    - title: "JavaScript"
      icon: "config/assets/icons/javascript.svg"
    - title: "React"
      icon: "config/assets/icons/react.svg"
    - title: "Node.js"
      icon: "config/assets/icons/nodejs.svg"
    - title: "MATLAB"
    - title: "MIPS"
    - title: "LaTeX"
    - title: "Notion"
      icon: "config/assets/icons/notion.svg"
    - title: "Adobe Illustrator"
      icon: "config/assets/icons/ai.svg"
    - title: "Final Cut Pro"
    - title: "Anaconda"
    - title: "Figma"
      icon: "config/assets/icons/figma.svg"
