# We are using the ionicons icon set https://ionic.io/ionicons
# For example, to add a linkedin icon:
# <ion-icon name="logo-linkedin"></ion-icon>
# - icon: "logo-linkedin"

HEADER:
  label: "Show Contacts"

USER:
  role: "Software Engineer"
  name: "Ashley Li"
  username: "ashleylyh" # <-- This needs to be the same as your GitHub username
  avatar: "config/assets/avatars/my-avatar.png"

INFO:
  - label: "Email"
    value: "yuhsi.1026@gmail.com"
    icon: "mail-outline"
  - label: "Phone"
    value: "+886 0988183646"
    icon: "phone-portrait-outline"
  - label: "Birthday"
    value: "Oct. 26, 2002"
    icon: "calendar-outline"
  - label: "Location"
    value: "Taiwan"
    icon: "location-outline"

SOCIAL:
  - icon: "logo-facebook"
    url: "https://facebook.com/"
  - icon: "logo-twitter"
    url: "https://twitter.com/"
  - icon: "logo-instagram"
    url: "https://instagram.com/"
  - icon: "logo-linkedin"
    url: "https://www.linkedin.com/ashleylyh"
  - icon: "logo-github"
    url: "https://github.com/ashleylyh"
