HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2015/8 - 2021/6"
      institution: "National Experimental High School at Hsinchu Science Park (Taiwan)"
      description: "Graduated with GPA 4.0/4.3, serve as the financial manager of Dance society and the Lead Coordinator of Joint-Club Annual Performance."
      coursework:
    - period: "2023/8 - 2024/1"
      institution: "Chalmers University of Technology (Sweden)"
      description: "Exchanged to Chalmers University of Technology in Sweden for one semester, focusing on advanced computer science courses and cultural experiences."
      coursework:
        - "Applied Signal Processing"
        - "Computer Graphic"
        - "Image Processing"
        - "Algorithm"
    - period: "2021/8 - 2025/7"
      institution: "The Hong Kong University of Science and Technology (Hong Kong)"
      description: "Graduated with Second Class Honours (Division One) in BEng in Computer Engineering with a minor in Big Data Technology."
      coursework:
        - "Machine Learning"
        - "Deep Learning in Computer Vision"
        - "Natural Language Processing"
        - "Parallel Programming"
        - "Computer Architecture"
        - "Operating Systems"
        - "Cloud Computing and Big Data Systems"
        - "Signal Processing"
        - "Object-Oriented Programming"


AWARD:
  enabled: true
  label: "Awards & Honors"
  items:
    - title: "HKSAR Government Scholarship - Reaching Out Award"
      date: "2023"
      description: "HKUST Undergraduate Exchanged Scholarship."

EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "2025/7 - Present"
      position: "Research Assistant @ Academia Sinica (Taiwan)"
      description: ""
    - period: "2024/7 - 2025/7"
      position: "Lead Project Coordinator @ HKUST Path Advisor"
      description: ""
    - period: "2024/6 - 2024/8"
      position: "Autonomous Driving Software Engineer Intern @ ITRI (Taiwan)"
      description: ""
    - period: "2023/6 - 2023/8"
      position: "Software Engineer Intern @ NovBee (Hong Kong)"
      description: ""
    - period: "2022/9 - 2024/7"
      position: "Frontend Developer @ HKUST Path Advisor"
      description: ""
    - period: "2022/7 - 2022/8"
      position: "Software Engineer Intern @ Wiadvance (Taiwan)"
      description: ""
    - period: "2022/6 - 2023/7"
      position: "Publicity Manager @ HKUST Taiwanese Students' Association"
      description: ""
    - period: "2022/9 - 2024/1"
      position: "UIUX Designer @ USThing"
      description: ""
    - period: "2021/9 - 2023/6"
      position: "Marketing Team Member @ HKUST Be Our Guest"
      description: ""

LANGUAGES:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items:
    - language: "Mandarin"
      proficiency: "100%"
    - language: "English"
      proficiency: "80%"
    - language: "Cantonese"
      proficiency: "30%"
    - language: "Korean"
      proficiency: "30%"

SKILLS:
  enabled: false
  display_progress_bars: true
  display_percentage_values: true
  label: "My Skills"
  items:
    - skill: ""
      proficiency: ""
